ERROR 2024-12-09 22:39:27,242 utils 12960 7260 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: POST
User: fx0883
Error Type: ValidationError
Error Message: {'priority': [ErrorDetail(string='“high” 不是合法选项。', code='invalid_choice')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\drf_spectacular\drainage.py", line 207, in wrapped_method
    return method(self, request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'priority': [ErrorDetail(string='“high” 不是合法选项。', code='invalid_choice')]}

    
ERROR 2024-12-09 23:14:58,263 utils 12960 18292 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/register/
Method: POST
User: fx0883
Error Type: ValidationError
Error Message: {'confirm_password': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\accounts\views.py", line 163, in register
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'confirm_password': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:16:47,876 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-09 23:17:01,552 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-09 23:17:03,582 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-09 23:17:54,624 utils 12960 27152 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-09 23:20:44,988 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-09 23:28:34,582 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:28:35,979 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:28:37,012 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:28:38,211 utils 12960 18292 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:38:53,399 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:38:54,704 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:38:57,450 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:39:05,822 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/6/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:39:06,955 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:39:07,414 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/6/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:43:08,341 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-09 23:43:16,878 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 00:03:13,192 utils 12960 34868 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/7/
Method: PUT
User: fx123
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 10:52:43,790 utils 3872 24784 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 10:52:43,798 utils 3872 24784 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 11:44:30,160 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:31,153 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:31,768 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:33,088 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:33,604 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:34,474 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:35,394 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 11:44:35,916 utils 3872 33540 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/11/
Method: PUT
User: fx0883
Error Type: ValidationError
Error Message: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\serializers.py", line 235, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'title': [ErrorDetail(string='该字段是必填项。', code='required')]}

    
ERROR 2024-12-10 13:48:50,869 basehttp 16456 24616 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:48:50,869 basehttp 16456 23964 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:48:51,133 basehttp 16456 21204 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:48:51,181 basehttp 16456 12532 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:48:51,181 basehttp 16456 16968 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:48:51,443 basehttp 16456 16216 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:12,672 basehttp 16456 10332 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:12,673 basehttp 16456 28620 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:12,937 basehttp 16456 28004 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:12,983 basehttp 16456 16920 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:12,983 basehttp 16456 8544 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:13,247 basehttp 16456 8916 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,353 basehttp 16456 7456 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,354 basehttp 16456 2484 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,618 basehttp 16456 24780 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,664 basehttp 16456 25268 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,665 basehttp 16456 14380 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:16,929 basehttp 16456 7196 You're accessing the development server over HTTPS, but it only supports HTTP.
ERROR 2024-12-10 13:51:43,889 utils 16456 19928 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:51:43,890 utils 16456 8276 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:51:43,900 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:51:43,901 utils 16456 8276 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:51:55,109 utils 16456 8276 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:51:55,112 utils 16456 8276 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:51:56,650 utils 16456 19928 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:51:56,650 utils 16456 8276 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:51:56,660 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:51:56,663 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:52:11,864 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:52:11,867 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:52:13,397 utils 16456 19928 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:52:13,398 utils 16456 8276 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:52:13,403 utils 16456 19928 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:52:13,417 utils 16456 8276 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:57:08,855 utils 2856 7732 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:57:08,862 utils 2856 7732 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:57:10,490 utils 2856 7732 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:57:10,490 utils 2856 8584 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 13:57:10,494 utils 2856 7732 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 13:57:10,497 utils 2856 7732 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/refresh/
Method: POST
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:09:58,399 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:18,533 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:19,223 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:19,590 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:20,270 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:20,697 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:33,876 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:36,371 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:36,784 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:37,040 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:37,244 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:37,455 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:37,663 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:37,868 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:10:38,120 utils 2856 15568 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: InvalidToken
Error Message: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 414, in initial
    self.perform_authentication(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 324, in perform_authentication
    request.user
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 227, in user
    self._authenticate()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 380, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 49, in authenticate
    validated_token = self.get_validated_token(raw_token)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\authentication.py", line 113, in get_validated_token
    raise InvalidToken(
rest_framework_simplejwt.exceptions.InvalidToken: {'detail': ErrorDetail(string='此令牌对任何类型的令牌无效', code='token_not_valid'), 'code': ErrorDetail(string='token_not_valid', code='token_not_valid'), 'messages': [{'token_class': ErrorDetail(string='AccessToken', code='token_not_valid'), 'token_type': ErrorDetail(string='access', code='token_not_valid'), 'message': ErrorDetail(string='令牌无效或已过期', code='token_not_valid')}]}

    
ERROR 2024-12-10 14:18:45,585 utils 6168 28208 
API Error Details:
View: TokenRefreshView
URL: /api/token/refresh/
Method: POST
User: AnonymousUser
Error Type: ParseError
Error Message: JSON parse error - Invalid control character at: line 3 column 245 (char 490)
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "D:\Software\python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Software\python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "D:\Software\python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Software\python\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 3 column 245 (char 490)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework_simplejwt\views.py", line 41, in post
    serializer = self.get_serializer(data=request.data)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Invalid control character at: line 3 column 245 (char 490)

    
ERROR 2024-12-10 14:24:53,539 utils 6168 27216 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:24:53,541 utils 6168 12876 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:25:05,153 utils 6168 12876 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: ParseError
Error Message: JSON parse error - Expecting value: line 1 column 1 (char 0)
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "D:\Software\python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Software\python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "D:\Software\python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Software\python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\accounts\views.py", line 210, in login
    serializer = LoginSerializer(data=request.data)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)

    
ERROR 2024-12-10 14:25:06,689 utils 6168 12876 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:25:06,689 utils 6168 27216 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:25:28,252 utils 6168 12876 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: ParseError
Error Message: JSON parse error - Expecting value: line 1 column 1 (char 0)
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "D:\Software\python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Software\python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "D:\Software\python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Software\python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\accounts\views.py", line 210, in login
    serializer = LoginSerializer(data=request.data)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)

    
ERROR 2024-12-10 14:25:29,793 utils 6168 12876 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:25:29,795 utils 6168 12876 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:28:48,245 utils 6168 12876 
API Error Details:
View: UserViewSet
URL: /api/v1/accounts/users/login/
Method: POST
User: AnonymousUser
Error Type: ParseError
Error Message: JSON parse error - Expecting value: line 1 column 1 (char 0)
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 64, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
  File "D:\Software\python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "D:\Software\python\Python310\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "D:\Software\python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Software\python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\accounts\views.py", line 210, in login
    serializer = LoginSerializer(data=request.data)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 216, in data
    self._load_data_and_files()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 279, in _load_data_and_files
    self._data, self._files = self._parse()
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\request.py", line 354, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\parsers.py", line 66, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting value: line 1 column 1 (char 0)

    
ERROR 2024-12-10 14:28:49,876 utils 6168 27216 
API Error Details:
View: TaskViewSet
URL: /api/v1/tasks/tasks/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
ERROR 2024-12-10 14:28:49,876 utils 6168 12876 
API Error Details:
View: CategoryViewSet
URL: /api/v1/tasks/categories/
Method: GET
User: AnonymousUser
Error Type: NotAuthenticated
Error Message: 身份认证信息未提供。
Stack Trace:
Traceback (most recent call last):
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
  File "D:\tmp\todo2\todoServer\.venv\lib\site-packages\rest_framework\views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: 身份认证信息未提供。

    
